### ISSUE TITLE
Rook has some of the moves restricted

### ISSUE THREAD

**Issue by AnushaSridharan** [Horopter/Game-AI#4]
![image](https://user-images.githubusercontent.com/5353215/89675770-1f850b00-d908-11ea-81a4-c0b1a36c9b83.png)
[rook-mov-restriction.log](https://github.com/Horopter/Game-AI/files/5043007/rook-mov-restriction.log)

**Comment by Horopter** [comment]
Fixed with [this](https://github.com/Horopter/Game-AI/commit/04ab335ead5bfe52cb4d282402d96d221af13cc9) change. Please check and close the issue
