### ISSUE TITLE
Pawn Movement

### ISSUE THREAD

**Issue by AnushaSridharan** [Horopter/Game-AI#5]
![image](https://user-images.githubusercontent.com/5353215/89678569-0af74180-d90d-11ea-92dc-6d89599aa718.png)

[pawn-f7-move.log](https://github.com/Horopter/Game-AI/files/5043171/pawn-f7-move.log)

White pawn is show F7 > F5 as a possible move when horse is present at F6

**Comment by Horopter** [comment]
Fixed with [this](https://github.com/Horopter/Game-AI/commit/991d92eef2a6e638e1620db58020337b63328a9f) change. Please verify and close.
